# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ece532/mid_demo/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_clk_wiz_1_0/mid_project_clk_wiz_1_0.xci
# IP: The module: 'mid_project_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ece532/mid_demo/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_clk_wiz_1_0/mid_project_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mid_project_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ece532/mid_demo/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_clk_wiz_1_0/mid_project_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mid_project_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ece532/mid_demo/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_clk_wiz_1_0/mid_project_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mid_project_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/ece532/mid_demo/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_clk_wiz_1_0/mid_project_clk_wiz_1_0.xci
# IP: The module: 'mid_project_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ece532/mid_demo/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_clk_wiz_1_0/mid_project_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mid_project_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ece532/mid_demo/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_clk_wiz_1_0/mid_project_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mid_project_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ece532/mid_demo/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_clk_wiz_1_0/mid_project_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mid_project_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
