# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Sam/Desktop/ECE532/mid_demo_v2/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_xbar_0/mid_project_xbar_0.xci
# IP: The module: 'mid_project_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sam/Desktop/ECE532/mid_demo_v2/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_xbar_0/mid_project_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mid_project_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Sam/Desktop/ECE532/mid_demo_v2/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_xbar_0/mid_project_xbar_0.xci
# IP: The module: 'mid_project_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sam/Desktop/ECE532/mid_demo_v2/mid_demo/mid_demo.srcs/sources_1/bd/mid_project/ip/mid_project_xbar_0/mid_project_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mid_project_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
